// <auto-generated />
using System;
using Employee_Attendance_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee_Attendance_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250320112057_InitialMySQLMigration")]
    partial class InitialMySQLMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Employee_Attendance_Api.Models.Dolgozo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FelhasznaloNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JelszoHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dolgozok");
                });

            modelBuilder.Entity("Employee_Attendance_Api.Models.HaviMunka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("DolgozoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LedolgozottIdoPerc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DolgozoId");

                    b.ToTable("HaviMunka");
                });

            modelBuilder.Entity("Employee_Attendance_Api.Models.Munkaora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BelepesIdo")
                        .HasColumnType("TEXT");

                    b.Property<int>("DolgozoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("KilepesIdo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DolgozoId");

                    b.ToTable("Munkaorak");
                });

            modelBuilder.Entity("Employee_Attendance_Api.Models.HaviMunka", b =>
                {
                    b.HasOne("Employee_Attendance_Api.Models.Dolgozo", "Dolgozo")
                        .WithMany()
                        .HasForeignKey("DolgozoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dolgozo");
                });

            modelBuilder.Entity("Employee_Attendance_Api.Models.Munkaora", b =>
                {
                    b.HasOne("Employee_Attendance_Api.Models.Dolgozo", "Dolgozo")
                        .WithMany()
                        .HasForeignKey("DolgozoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dolgozo");
                });
#pragma warning restore 612, 618
        }
    }
}
